"""Add cascade

Revision ID: 81502994accf
Revises: 4ede4ae40ee2
Create Date: 2023-06-12 15:28:59.128089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81502994accf'
down_revision = '4ede4ae40ee2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
